version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: brook
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
